export const FETCH_INSTAGRAM_DATA_BEGIN = 'FETCH_INSTAGRAM_DATA_BEGIN';
export const FETCH_INSTAGRAM_DATA_SUCCESS = 'FETCH_INSTAGRAM_DATA_SUCCESS';
export const FETCH_INSTAGRAM_DATA_FAILURE = 'FETCH_INSTAGRAM_DATA_FAILURE';

export const FETCH_INSTAGRAM_PAGE_DATA_BEGIN = 'FETCH_INSTAGRAM_PAGE_DATA_BEGIN';
export const FETCH_INSTAGRAM_PAGE_DATA_SUCCESS = 'FETCH_INSTAGRAM_PAGE_DATA_SUCCESS';
export const FETCH_INSTAGRAM_PAGE_DATA_FAILURE = 'FETCH_INSTAGRAM_PAGE_DATA_FAILURE';

export const TOGGLE_MODAL_OPEN = 'TOGGLE_MODAL_OPEN';
export const TOGGLE_MODAL_CLOSED = 'TOGGLE_MODAL_CLOSED';

export const INSTAGRAM_POST_TYPE_IMAGE = 'INSTAGRAM_POST_TYPE_IMAGE';
export const INSTAGRAM_POST_TYPE_VIDEO = 'INSTAGRAM_POST_TYPE_VIDEO';
export const INSTAGRAM_POST_TYPE_CAROUSEL = 'INSTAGRAM_POST_TYPE_CAROUSEL';

export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const IS_MOBILE = 'IS_MOBILE';

export const VIDEO_PLAYING = 'VIDEO_PLAYING';
export const VIDEO_PAUSED = 'VIDEO_PAUSED';

export const NAVIGATION_CHANGE_TYPES = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
    SCROLLED_TO_TARGET: 'SCROLLED_TO_TARGET',
    NOT_SCROLLED_TO_TARGET: 'NOT_SCROLLED_TO_TARGET'
};

export const INSTAGRAM_CHANGE_TYPES = {
    NEXT_POST: 'NEXT_POST',
    PREV_POST: 'PREV_POST',
    NEXT_CAROUSEL_POST: 'NEXT_CAROUSEL_POST',
    PREV_CAROUSEL_POST: 'PREV_CAROUSEL_POST'
};
